import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import crypto from 'node:crypto'
import { createDurableStateStore } from '../src/store.js'
import { createDurableQueue } from '../src/queue.js'
import { createMarketingAgent, detectControlIntent } from '../src/marketing.js'
import { extractCloudMessages, verifyMetaSignature } from '../src/whatsapp-cloud.js'
import { createMetrics } from '../src/metrics.js'

function config() { return { enabled:true, configured:true, requireKnowledge:true, agentName:'Agent', agentRole:'conversation marketing assistant', companyName:'CopyToLive', business:'Verified product context', valueProposition:'Verified value', purpose:'qualify', cta:'book a demo', locale:'id-ID', maxTurns:6, ttlMs:60_000, maxInputChars:6000, optOutMessage:'OPTED OUT', handoffMessage:'HANDOFF', optInMessage:'OPTED IN' } }
const knowledge = { facts:['Harga hanya boleh disebut jika ada di fakta.'], source:'test', configured:true, context:'1. Harga hanya boleh disebut jika ada di fakta.' }
function tempStore() { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'chat-ai-test-')); return { dir, store:createDurableStateStore({ filePath:path.join(dir,'state.json') }) } }
function mockComplete(messages) { const latest = messages.at(-1)?.content || ''; const stage = /mahal|keberatan/i.test(latest) ? 6 : /beli|demo|meeting/i.test(latest) ? 7 : 3; return JSON.stringify({ stage, lead_score:stage===7?80:stage===6?55:40, handoff:false, next_action:'continue', reply:`Reply for ${latest.slice(0,40)}` }) }

test('control intents are deterministic',()=>{ assert.equal(detectControlIntent('STOP'),'opt_out'); assert.equal(detectControlIntent('jangan hubungi saya'),'opt_out'); assert.equal(detectControlIntent('admin tolong'),'human_handoff'); assert.equal(detectControlIntent('mulai lagi'),'opt_in') })
test('durable opt-out survives a fresh agent instance',async()=>{ const {dir,store}=tempStore(); const first=createMarketingAgent({complete:mockComplete,config:config(),knowledge,store}); const result=await first.processDetailed({jid:'6281',text:'stop'}); assert.equal(result.event,'opt_out'); assert.equal(result.state.optedOut,true); const secondStore=createDurableStateStore({filePath:path.join(dir,'state.json')}); const second=createMarketingAgent({complete:mockComplete,config:config(),knowledge,store:secondStore}); const suppressed=await second.processDetailed({jid:'6281',text:'halo lagi'}); assert.equal(suppressed.reply,null); assert.equal(suppressed.event,'suppressed_opt_out'); const resumed=await second.processDetailed({jid:'6281',text:'mulai lagi'}); assert.equal(resumed.event,'opt_in'); assert.equal(resumed.state.optedOut,false) })
test('durable state hashes contact identifiers at rest',()=>{ const {dir,store}=tempStore(); store.setOptOut('628123456789@s.whatsapp.net',true); const raw=fs.readFileSync(path.join(dir,'state.json'),'utf8'); assert.equal(raw.includes('628123456789'),false); assert.equal(store.stats().contactIdentifiers,'sha256') })
test('human handoff persists and can be resumed explicitly by admin path',async()=>{ const {store}=tempStore(); const agent=createMarketingAgent({complete:mockComplete,config:config(),knowledge,store}); const handoff=await agent.processDetailed({jid:'6282',text:'saya mau bicara dengan admin'}); assert.equal(handoff.event,'human_handoff'); assert.equal((await agent.processDetailed({jid:'6282',text:'halo'})).reply,null); assert.equal(agent.resumeHumanHandoff('6282').handoff,false); assert.match((await agent.processDetailed({jid:'6282',text:'halo'})).reply,/Reply for/) })
test('Meta webhook signature validation and message extraction work',()=>{ const body=Buffer.from(JSON.stringify({object:'whatsapp_business_account',entry:[{changes:[{value:{metadata:{phone_number_id:'123'},messages:[{id:'wamid.1',from:'62811',text:{body:'Halo'}}]}}]}]})); const secret='secret'; const signature=`sha256=${crypto.createHmac('sha256',secret).update(body).digest('hex')}`; assert.equal(verifyMetaSignature(body,signature,secret),true); assert.equal(verifyMetaSignature(body,'sha256=bad',secret),false); assert.deepEqual(extractCloudMessages(JSON.parse(body.toString('utf8'))),[{jid:'62811',text:'Halo',messageId:'wamid.1',phoneNumberId:'123'}]) })
test('encrypted durable queue hides contact payload and deduplicates after processing',async()=>{ const dir=fs.mkdtempSync(path.join(os.tmpdir(),'chat-ai-queue-')); const queue=createDurableQueue({dir,encryptionKey:'0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef'}); const message={jid:'6281999',text:'rahasia prospek',messageId:'wamid.queue'}; assert.equal(queue.enqueue(message,{id:message.messageId}).duplicate,false); const queuedFile=fs.readdirSync(dir).find((name)=>name.endsWith('.queue')); const raw=fs.readFileSync(path.join(dir,queuedFile),'utf8'); assert.equal(raw.includes('6281999'),false); assert.equal(raw.includes('rahasia prospek'),false); assert.equal(queue.enqueue(message,{id:message.messageId}).duplicate,true); let handled=0; await queue.drainOnce(async()=>{handled+=1}); assert.equal(handled,1); assert.equal(queue.enqueue(message,{id:message.messageId}).duplicate,true); assert.equal(queue.stats().encrypted,true) })
test('metrics expose p50/p95 and counters',()=>{ const metrics=createMetrics(); metrics.inc('messagesReceived',2); metrics.inc('repliesSent'); metrics.observeLatency(10); metrics.observeLatency(100); const snapshot=metrics.snapshot(); assert.equal(snapshot.messagesReceived,2); assert.equal(snapshot.repliesSent,1); assert.equal(snapshot.p95LatencyMs,100) })
test('1000-case launch acceptance contract',async()=>{ const {store}=tempStore(); const agent=createMarketingAgent({complete:mockComplete,config:config(),knowledge,store}); let normal=0,objections=0,optouts=0,handoffs=0; for(let i=0;i<1000;i+=1){ const group=i%4,jid=`case-${i}`; if(group===0){const r=await agent.processDetailed({jid,text:`Saya tertarik paket untuk tim #${i}`});assert.equal(r.event,'reply');assert.equal(r.state.stage,3);normal+=1}else if(group===1){const r=await agent.processDetailed({jid,text:`Menurut saya mahal, keberatan #${i}`});assert.equal(r.event,'reply');assert.equal(r.state.stage,6);objections+=1}else if(group===2){const r=await agent.processDetailed({jid,text:`STOP #${i}`});assert.equal(r.event,'opt_out');assert.equal(r.state.optedOut,true);optouts+=1}else{const r=await agent.processDetailed({jid,text:`admin tolong #${i}`});assert.equal(r.event,'human_handoff');assert.equal(r.state.handoff,true);handoffs+=1}} assert.deepEqual({normal,objections,optouts,handoffs},{normal:250,objections:250,optouts:250,handoffs:250}) })
